### ISSUE TITLE
Runtime crash with beta08

### ISSUE THREAD

**Issue by Vivecstel** [Gurupreet/FontAwesomeCompose#2]
Tried the library with compose beta08 and I am getting the following runtime crash:

```
Process: com.steleot.jetpackcompose.playground, PID: 31429
    java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer; in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/~~dHRVawyRs3mwUptpciOClg==/com.steleot.jetpackcompose.playground-g0g0XfGqKnBxgUvZAZL-Gg==/base.apk)
        at com.guru.fontawesomecomposelib.FaIconKt.FaIcon-EfRbmQ0(FaIcon.kt:35)
        at com.steleot.jetpackcompose.playground.compose.externallibraries.FontAwesomeScreenKt.FontAwesomeGrid(FontAwesomeScreen.kt:116)
        at com.steleot.jetpackcompose.playground.compose.externallibraries.FontAwesomeScreenKt.access$FontAwesomeGrid(FontAwesomeScreen.kt:1)
        at com.steleot.jetpackcompose.playground.compose.externallibraries.ComposableSingletons$FontAwesomeScreenKt$lambda-1$1.invoke(FontAwesomeScreen.kt:22)
        at com.steleot.jetpackcompose.playground.compose.externallibraries.ComposableSingletons$FontAwesomeScreenKt$lambda-1$1.invoke(FontAwesomeScreen.kt:21)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:316)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:314)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
```

**Comment by mustnap** [comment]
i am getting the same error. any way that we can recompile the library ourselves?

**Comment by Gurupreet** [comment]
Hi let me check it up today and update. Sorry for the issues

**Comment by mustnap** [comment]
i think the instruction just needs updating.

`    implementation 'com.github.Gurupreet:FontAwesomeCompose:1.0.0-beta01'`

**Comment by Gurupreet** [comment]
Yes I will still update it to latest beta version but beta01 should work

**Comment by Gurupreet** [comment]
Updated to beta09 please use 1.0.0-beat02 👍🏽

**Comment by Nailik** [comment]
I get the same crash with 1.0.0-beta01 and 1.0.1-alpha01
